[RFC] Adds Ping() to client/scheduler/server
hibiken/asynq pull request #585
Opened 2022-12-14 00:08 UTC by pbarnum

2022-12-14 16:55 UTC, pbarnum commented
@hibiken, this should close #445

2022-12-28 11:14 UTC, mdaliyan commented
Right now I'm pushing a task with an empty payload and then I'm ignoring it when I consume it for the sake of health check. Exposing Ping makes it much easier and cleaner health check than my approach. Please consider increasing the priority for this PR if possible. Thank you.

2023-06-14 13:08 UTC, rapita approved these changes

2023-11-12 22:45 UTC, bojanz commented
@hibiken What can we do to push this along? I need a client.Ping() to be able to integrate into my app's health check metrics.

2024-04-12 17:33 UTC, arpitflex commented
We are deploying an asynq queue alongside our services in a Kubernetes cluster, and a readiness check like this would be very helpful to ensure better Pod restarts by the orchestrator. Are we looking to include this with the 0.25 release @hibiken?

2024-04-13 04:34 UTC, kamikazechaser requested changes

2024-04-13 04:34 UTC, kamikazechaser commented on scheduler.go
> +func (s *Scheduler) Ping() error {
Check for s.srvStateClosed here as well

2024-10-19 06:44 UTC, merged