Fix memory leaks caused by time.After
hibiken/asynq pull request #914
Opened 2024-09-03 14:58 UTC by biningo

Fixes #913

2024-09-12 14:06 UTC, l0nax requested changes

2024-09-12 14:06 UTC, l0nax commented on subscriber.go
Only starting with Go 1.23 unreferenced and unstopped `time.Ticker` will be garbage collected.

Since the min. Go version of this project is Go 1.20, you should call `defer ticker.Stop()`. Otherwise, this will leak the ticker.

In both cases, the changed code does not behave the same as the original one: `time.Ticker` publishes in a defined Interval $I$. You have to reset the ticker every time you start the next "cycle. "Otherwise, the timeout you're waiting for may be shorter than expected.

2024-09-22 13:31 UTC, biningo commented on subscriber.go
Thank you for your suggestions! : )  
I'll fix it!

**About Go version**
As you said, using time.After in Go 1.23 and later versions does not cause memory leaks, but this project is using Go 1.20.

**About ticker or timer**
The ticker sends values to the channel at a fixed rate. If the task execution time is longer than the ticker interval, the next task will start immediately after the previous task finished.
But the timer can be reset after the task has finished. No matter how long the previous task is running, the next task will start after the interval.

2024-10-02 08:55 UTC, huangc28 commented
Why haven't we merge this PR?

2024-10-19 08:08 UTC, kamikazechaser commented
Thanks @biningo, we will migrate this library to v1.23 soon.

2024-10-26 10:24 UTC, kamikazechaser commented on syncer.go
> +		timer := time.NewTimer(s.interval)
In the syncer, would it be more appropriate for the initialized Interval to be 0 while the Reset to then use the s.interval value?

2024-10-26 10:27 UTC, kamikazechaser commented
If we were to move this library to 1.23, this change wouldn't be required at all. I am not sure if this optimization is worth it (at the expense of code complexity) for what could possibly be 2 months (or even less).

cc/ @pior @l0nax

2024-10-26 13:48 UTC, biningo commented
> If we were to move this library to 1.23, this change wouldn't be required at all. I am not sure if this optimization is worth it (at the expense of code complexity) for what could possibly be 2 months (or even less).
> 
> cc/ @pior @l0nax

Upgrading to Go 1.23 is a better solution.

2024-10-27 05:14 UTC, kamikazechaser commented
Sounds good. I'll close this for now. Thanks for highlighting this though!

2024-10-27 05:14 UTC, closed without merging